# Generated by Django 5.1.2 on 2024-12-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_subcategory_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['order'], 'verbose_name': 'Slider Resmi', 'verbose_name_plural': 'Slider Resimleri'},
        ),
        migrations.RemoveField(
            model_name='slider',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='updated_at',
        ),
    ]
