# Generated by Django 5.1.2 on 2024-12-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_slider_options_remove_slider_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlık'),
        ),
    ]
