# Generated by Django 5.1.2 on 2024-12-18 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_slider_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['order'], 'verbose_name': 'Tanıtım Resmi', 'verbose_name_plural': 'Tanıtım Resimleri'},
        ),
    ]
